name = "jewelry-estimator"
compatibility_date = "2025-09-05"
pages_build_output_dir = "./public"

[[d1_databases]]
binding = "DB"
database_name = "jewelry_estimator_db"
database_id = "b66485af-5727-424b-bb1e-655b26fd4804"

[vars]
CORS_ORIGIN = "https://www.baiyoke99.com"